config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {:registrations => "registrations", :confirmations => 'confirmations'}

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'

  resources :users

  get 'forgot_password/forgot'

  get 'pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'

  # makes /login go to the login page
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  # makes /signup go to the signup page
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  # makes /signup go to the signup page
  devise_scope :user do
    get 'edit', to: 'devise/registrations#edit'
  end

  get '/search' => 'pages#search', :as => 'search_page'

  post 'users/search' => 'users#search', as: 'search_user'

  resources :registration_steps
  resources :event_infos

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  def new
  end
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    registration_steps_path
  end
end

app/controllers/event_infos_controller.rb
class EventInfosController < ApplicationController
	def index
	end
end

app/controllers/forgot_password_controller.rb
class ForgotPasswordController < ApplicationController
  def forgot
  end

  def send_email
  	if params[:search].blank?
    		redirect_to(root_path, alert: 'Empty field!') and return
    else
    	@parameter = params[:search].downcase
    		#@results = User.where('lower(email) LIKE :search', search: @parameter)
    		@results = User.exists('email LIKE :search', search: @parameter)
  	end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @user1970 = User.where('year < 1980 AND year > 1960')
    @user1980 = User.where('year < 1990 AND year > 1979')
    @user1990 = User.where('year < 2000 AND year > 1989')
    @user2000 = User.where('year < 2010 AND year > 1999')
    @user2010 = User.where('year < 2020 AND year > 2009')
  end

 	def search
  		if params[:search].blank?
    		redirect_to(root_path, alert: 'Empty field!') and return
  		else
    		@parameter = params[:search].downcase+'%'
    		@results = User.where('lower(firstname) LIKE :search OR lower(lastname) LIKE :search OR year LIKE :search OR lower(business) LIKE :search or lower(email) LIKE :search OR lower(location) LIKE :search', search: @parameter).order(:year)
		end

	end
end

app/controllers/registration_steps_controller.rb
class RegistrationStepsController < ApplicationController
  include Wicked::Wizard
  steps :information, :biography, :availability

  def new
    @user = User.new
  end

  def create
      @user = User.new(params[:sign_up])
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_steps_path
      else
        redirect_to new_user_registration_path
      end
    end

  def show
    @user = current_user
    render_wizard
  end

  def update
    @user = current_user
    @user.update_attributes(user_params)
    render_wizard @user
  end

  private
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :bio, :year, :location, :business, :degrees, :share, :mentor, :image, :contact, :attending)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
  end

  def after_sign_up_path_for(resource)
    new_confirmation_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    confirmation_path(resource)
  end

    private

    def sign_up_params
      params.require(:user).permit( :firstname,
                                    :lastname,
                                    :email,
                                    :bio,
                                    :year,
                                    :location,
                                    :password,
                                    :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit( :firstname,
                                    :lastname,
                                    :email,
                                    :bio,
                                    :year,
                                    :location,
                                    :password,
                                    :password_confirmation,
                                    :current_password)
    end

  end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    if params[:name]
      @user = User.where('name LIKE ?', "%#{params[:name]}%")
    else
      @user = User.all
    end
  end

  def edit
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
  end

  def search
    @q = "%#{params[:query]}%"
    @user = User.where("firstname LIKE ? or lastname LIKE ? or year LIKE ? or location LIKE ?", @q, @q, @q, @q)
    render 'index'
  end

  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :bio, :year, :location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/event_infos_helper.rb
module EventInfosHelper
end

app/helpers/forgot_password_helper.rb
module ForgotPasswordHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registration_steps_helper.rb
module RegistrationStepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer updated 04/03/19 -->

<footer id = "this-footer">
  <br>
  <div class="container-fluid">
      <div class="row put-margin">
          <div class="col-xl-3">
            <a href="https://www.bgsu.edu">
                <img src="//services.bgsu.edu/bgsulibs/theme/1.1.0/images/logo.png" alt="Footer Logo">
              </a>
                <p class="footer-date">
                  Bowling Green State University<br>
                  Bowling Green, Ohio<br>
                  43403-0001 <br>
                  419-372-2531
                </p>
              <div class="footer-social social_links parbase">

              </div>
              <p class="footer-date" style="clear:both;padding-top: 15px;">
                <a href="http://www.bgsu.edu/give" target="_blank">
                  <span class="search-text white-link">Make A Gift</span>
                  <span class="ss-icon ss-pika" style="vertical-align: middle;"></span>
      </a>
              </p>
          </div>

          <div class="col-xl-3">
            <ul class="footer-nav link-white" style = "list-style: none; clear: left; line-height: 20px;">
                <li><a href="https://www.bgsu.edu/a-z-links.html"><strong>A-Z Links</strong></a></li><br>
                <li><a href="https://www.bgsu.edu/students.html"><strong>Students</strong></a></li><br>
                <li><a href="https://www.bgsu.edu/faculty-staff.html"><strong>Faculty/Staff</strong></a></li><br>
                <li><a href="https://www.bgsu.edu/parents.html"><strong>Parents</strong></a></li><br>
                <li><a href="https://www.bgsu.edu/employment.html"><strong>Employment</strong></a></li><br>
                <li><a href="https://www.bgsu.edu/library.html"><strong>Libraries</strong></a></li><br>
                <li><a href="http://www.firelands.bgsu.edu/"><strong>Firelands</strong></a></li><br>
                <li><a href="https://services.bgsu.edu/directorySearch/search.htm"><strong>Directory</strong></a></li><br>
                <li><a href="https://www.bgsu.edu/its.html"><strong>Technology Support</strong></a></li><br>
              </ul>
          </div>

          <div class="col-xl-6">
            <p style="font-size: 14px; line-height: 1.4em; font-family: 'Verb'">
              <strong>ACCESSIBILITY</strong>
            </p>
            <p style="font-size: 14px;"><a href="/accessibility.html"><span class="fa fa-wheelchair-alt" style="vertical-align: middle;" aria-hidden="true"></span><strong>Report an Issue</strong></a></p>
            <p style="font-size: .8em; line-height: 1.4em; font-family: 'Verb'"><strong>Accessibility Enhanced Pages</strong></p>
            <p style="font-size: .8em; line-height: 1.4em; font-family: 'Verb'">BGSU offers alternative versions of all of its pages for our users. You can select the high-contrast version below to persist throughout your BGSU website experience.
            </p>
            <p style="font-size: 14px;cursor: pointer;" class = "like-link"><a onclick="changeBodyBg('WhiteSmoke', 'white', '#2E271E', '#212529', '#FF7300', '#2d261d');"><span class="fa fa-wheelchair-alt" style="vertical-align: middle;" aria-hidden="true"></span><strong>High Contrast Colors</strong></a></p>
            <p style="font-size: 12px; line-height: 1.4em; font-family: 'Verb'">Bowling Green State University (BGSU) has built its website around the Standards of the World Wide Web Consortium's (W3C) Hyper Text Markup Language (HTML) 5 and Cascading Style Sheets (CSS). The website was built in compliance with the accessibility standards established by section 508 of the Rehabilitation Act and detailed in section 1194.22 of the Code of Federal Regulations, "Web-based intranet and internet information and applications" (<a href="https://www.section508.gov/">https://www.section508.gov/</a>).</p>

            <p style="font-size: 12px; line-height: 1.4em; font-family: 'Verb'">BGSU utilizes many webmasters across campus to maintain all of its web properties. Keeping the BGSU website in compliance with section 508 is a joint effort between Accessibility Services, Marketing and Communications and Information Technology Services. If any page is discovered to be inaccessible, please report it using the above link and we will ensure that the issue is addressed.</p>

            <p style="font-size: 14px; line-height: 1.4em; font-family: 'Verb'"><strong>EVENTS</strong></p>

            <p style="font-size: 12px; line-height: 1.4em; font-family: 'Verb'">To our guests with disabilities, please indicate if you need special services, assistance or appropriate modifications to fully participate in this event by contacting&nbsp;Accessibility Services, <a href="mailto:access@bgsu.edu">access@bgsu.edu</a>, 419-372-8495. Please notify us prior to the event.</p>

            <p style="color: #636363;"></p>
          </div>
      </div>
    </div>
  </footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg fixed-top" id = "navbar">
  <!-- Brand -->
  <a class=" navbar-nav navbar-brand" href="https://www.bgsu.edu">
  	<%= image_tag("logo.png", alt: "BGSU logo") %>
  </a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-light navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
		  <% if user_signed_in? %>
		  <ul class="navbar-nav">
			<li class="nav-item">
			  <%= link_to "Home", root_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
			  <%= link_to "Alumni Portal", users_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link"  %>
			</li>
			<li class="nav-item">
				<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<pre>          </pre><!-- literally blank space bc search form wouldnt right align -->
			</li>
    </ul>
      <ul class = "navbar-nav ml-auto">
			<li class="nav-item justify-content-center">
			<%= form_tag(search_page_path, :method => "get", class: '') do %>
  				<li class="input-group" style = "width: 100%;">
    				<%= search_field_tag :search, params[:search], placeholder: "Search For Alumni", class: "form-control" %>
    				<div class="input-group-btn">
      					<%= button_tag "Search", :class => 'btn-info btn glyphicon glyphicon-search',:name => nil%>
    				</div>
    			</li>
 			</li>
    </ul>
<% end %>

		  <% else # user not signed it %>
		  <ul class="navbar-nav">
			<li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
			</li>
			<li class="nav-item">
				<%= link_to 'Register', new_user_registration_path, class: "nav-link"  %>
			</li>
		  </ul>

      <% end %>
  </div><!-- navbar-collapse -->


  <div class="collapse navbar-collapse" id="collapsibleNavbar">

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang = "en">
  <head>
    <title>50th Year Anniversary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>BGSU Computer Science | 50th Anniversary</title>
	  <meta charset="utf-8">
	  <meta name="viewport" content="width=device-width, initial-scale=1">

	  <!-- Bootstrap CSS -->
	  <link rel="stylesheet" href="CSS-pages/bootstrap.css">
	  <link rel="stylesheet" href="CSS-pages/testStyle.css">

	  <!-- Other Things -->
	  <meta name = "description" content = "ASF Challenge website">
	  <meta name = "keywords" content = "BGSU, Bowling Green, ASF Sprint Challenge, Computer Science, 50 year anniversary">
	  <meta name = "authors" content = "Benjamin Spisak, Adam Coger">

		<!-- favicon -->
		<%= favicon_link_tag asset_path('bgsuIcon.png'), :rel => 'icon', :type =>  'image/png' %>
	  <link rel="apple-touch-icon" sizes="180x180" href="images/apple-touch-icon.png">
	  <link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png">
	  <link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png">
	  <link rel="manifest" href="/site.webmanifest">
	  <link rel="mask-icon" href="images/safari-pinned-tab.svg" color="#5bbad5">
	  <meta name="msapplication-TileColor" content="#da532c">
	  <meta name="theme-color" content="#ffffff">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang = "en">

<!-- Body of Home Page -->
<body>
		<!-- Logo over picture on home page -->

	<section id="FiftyYear">
		<div class="container-fluid d-flex align-items-center h-100 justify-content-center">
			<div class = "CSLogo img-fluid put-margin">
				<%= image_tag("letscelebrate.png", :class => "img-fluid", :alt => "BGSU CS 50th Year Anniversary") %>
			</div>
		</div>

	</section>
	<br>

	<section id = "Desciption">
		<div class="container-fluid">
        	<div class="row put-margin">

			<!-- Body Paragraph, probs need to refine this -->
				<div class = "col-lg-8">
					<br>
					<h3 class="text-heading turn-color" id="text-heading"> 50 Years of Computing</h3>

					<p id = "homepage-bodytext"> Since 1969, the Bowling Green Computer Science Department has provided an environment for students
				and faculty alike to pursue their careers in our technological world and advance towards the cutting edge of computing.
				50 years ago, Bowling Green State University realized the potential of computers to change the world and founded our
				department with the vision of producing alumni prepared to enter a workforce with rapidly changing needs. We now celebrate
				the achievements of the last 50 years.
					<br><br>
					Going to the alumni portal will allow you to see all your fellow Falcons who are coming to the event. You can either
					search for specific people, or just get a general sense of the alumni you will see at the event.
					<br><br>
					You may also search for different alumni that are attending the event. This is as simple as making an account and then, once logged in,
					searching for someone by first name, last name, current location, and year graduated.
					<br><br>
					Join us as we come together to share memories and revel in the accomplishments of BGSU’s Department of
				Computer Science. Find and connect with those friends and colleagues that you haven’t met with for a while. Learn about
				the history of our department and those who have been a part of it for so many years. We are proud to invite you to come
				participate in the celebration of providing quality Computer Science education for half of a century.
                </div>

                <div class="col-lg-4 justify-content-center" style = " width = 100%; min-height: 380px;">
                    <!-- Twitter feed integration -->
                    <a class="twitter-timeline" data-width="400" data-height="100%" href="https://twitter.com/BGSU_CS" style= "background-color: blue;">Tweets by bgsu_asf</a>
                    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                </div>
			</div>
		</div>
		<br>
		<div class = "containder-fluid d-flex justify-content-center">
			<div class = "row">
				<div class="col-md-6 justify-content-center">
					<%= image_tag("nationwide-sponsor.png", :class => "img-fluid", :alt => "Nationwide", :style => "max-width:100%; max-height:100%") %>
				</div>
				<div class="col-md-6 justify-content-center">
					<%= image_tag("its-sponsor.png", :class => "img-fluid", :alt => "BGSU ITS", :style => "max-width:100%;max-height:100%") %>
				</div>
			</div>
		</div>
		<br>
	</section>

	<section id = "Leave">
		<div class = "put-margin">
			<div class="container-fluid d-flex justify-content-center">
				<div class="row">
					<div class="col-md-6 justify-content-center">
						<div class="card" style="min-height: 14.5rem; width: 18rem;">
							<div class="card-body">
								<h5 class="card-title">Alumni Portal</h5>
								<p class="card-text">Learn about other attendees coming to the event and see who is coming from your class.</p>
								<br>
								<%= link_to "<button class = 'btn-info btn' style = 'width: 110px; position: relative; bottom: 4%'>Go</button>".html_safe, users_path, class: "color-blue" %>
							</div>
						</div>
					</div>

					<div class="col-md-6 justify-content-center">
						<div class="card" style="min-height: 14.5rem; width: 18rem;">
							<div class="card-body">
								<h5 class="card-title">Confirmed Guests Who Graduated In:</h5>
								<div class = "row">
									<div class = "col-sm-6">
										<p class="card-text">1969 - 1979: <%= @user1970.count %></p>
										<p class="card-text">1980 - 1989: <%= @user1980.count %></p>
										<p class="card-text">1990 - 1999: <%= @user1990.count %></p>
									</div>
									<div class = "col-sm-6">
										<p class="card-text">2000 - 2009: <%= @user2000.count %></p>
										<p class="card-text">2010 - 2019: <%= @user2010.count %></p>
										<% if user_signed_in? %>
											<%= link_to "<button class = 'btn-info btn' style = 'width:110px;'>See Them!</button>".html_safe, users_path, class: "color-blue" %>
										<% else # user not signed it %>
											<%= link_to "<button class = 'btn-info btn' style = 'width:110px;'>Register!</button>".html_safe, new_user_registration_path, class: "color-blue" %>
										<% end %>
									</div>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
			<br><br>
		</div>
	</section>
<br> <br>
</body>

</html>

app/views/pages/search.html.erb
<p id = "homepage-bodytext"></p>
<br><br>
<% if @results.count == 2 %>
	<section>
		<h2 class = "put-margin turn-color text-center" id = "text-heading"><strong>Search Results (Ordered by Year Graduated)</strong></h2><br>
	  <div class = "put-margin">
	    <div class="container-fluid d-flex justify-content-center">
	      <div class="row">
	        <% @results.each do |result| %>
	          <div class="col-lg-6">
	            <div class="card" style="width: 18rem; height: 280px;">
	              <div class="card-body">
	                <h5 class="card-title clearfix do-wrap"><span class = "valign do-wrap"><%= result.firstname %> <%= result.lastname %></span><div class = "circle pull-right">
	                  <% if result.image_url == nil %>
	                    <%= image_tag("default-picture.png") %>
	                  <% else %>
	                    <%= image_tag(result.image_url(:thumb)) %>
	                  <% end %>
	                </div></h5>
									<p class="card-text"><strong>Year Graduated: </strong><%= result.year %><br><strong>Location: </strong><%= result.location %>
									<br><strong>Highest Degree at BG: </strong><%= result.degrees %></p>
									<% if result.degrees == "Other" %>
										<br>
									<% end %>
	                <%= link_to "<button class = 'btn-info btn'>See More</button>".html_safe, user_path(result), class: "other-blue" %>
	              </div>
	            </div>
							<br>
	          </div>
	        <% end %>
	      </div>
	    </div>
	    <br><br>
	  </div>
	</section>
<% end %>

<% if @results.count != 2 %>
	<section>
		<h2 class = "put-margin turn-color text-center" id = "text-heading"><strong>Search Results (Ordered by Year Graduated)</strong></h2><br>
	  <div class = "put-margin">
	    <div class="container-fluid d-flex justify-content-center">
	      <div class="row">
	        <% @results.each do |result| %>
	          <div class="col-lg-4">
	            <div class="card" style="width: 18rem; height: 280px;">
	              <div class="card-body">
	                <h5 class="card-title clearfix do-wrap"><span class = "valign do-wrap"><%= result.firstname %> <%= result.lastname %></span><div class = "circle pull-right">
	                  <% if result.image_url == nil %>
	                    <%= image_tag("default-picture.png") %>
	                  <% else %>
	                    <%= image_tag(result.image_url(:thumb)) %>
	                  <% end %>
	                </div></h5>
									<p class="card-text"><strong>Year Graduated: </strong><%= result.year %><br><strong>Location: </strong><%= result.location %>
									<br><strong>Highest Degree at BG: </strong><%= result.degrees %></p>
									<% if result.degrees == "Other" %>
										<br>
									<% end %>
	                <%= link_to "<button class = 'btn-info btn'>See More</button>".html_safe, user_path(result), class: "color-blue" %>
	              </div>
	            </div>
							<br>
	          </div>
	        <% end %>
	      </div>
	    </div>
	    <br><br>
	  </div>
	</section>
<% end %>

	<br><br><br>
	<br><br><br>
	<br><br><br>
	<br><br><br>
	<br><br><br>